.TH a 1 "3.06.2023" "Wersja 1.0" "Adam Pacek"
.SH NAZWA
a \- skrypt analizujący plik GPX
.SH SPOSÓB UŻYCIA
.B a
[\-v] [\-h] [\-l] [\-t] [\-a] [\-r] [\-x] [\-m]
.I nazwa_pliku.gpx
.SH OPIS
Skrypt a analizuje pliki GPX, obliczając różne parametry trasy. Może obliczać długość trasy, czas trwania, średnią prędkość, średni puls, maksymalną prędkość i maksymalny puls.
.SH OPCJE
.TP
.B \-v
Wyświetla informacje o wersji skryptu.
.TP
.B \-h
Wyświetla pomoc.
.TP
.B \-l
Oblicza długość trasy.
.TP
.B \-t
Oblicza czas trwania.
.TP
.B \-a
Oblicza średnią prędkość.
.TP
.B \-r
Oblicza średni puls.
.TP
.B \-x
Znajduje maksymalną prędkość.
.TP
.B \-m
Znajduje maksymalny puls.
.SH PRZYKŁADY
\fBa \-l \-a \-x trasa.gpx\fR
.PP
Uruchamia skrypt, oblicza długość trasy, średnią prędkość i znajduje maksymalną prędkość w pliku \fItrasa.gpx\fR.
.SH BUGS
Brak znanych błędów w tym skrypcie. O błędach poinformuj na adres adam@pacek.it
.SH AUTOR
Adam Pacek (adam@pacek.it)
.SH ZOBACZ RÓWNIEŻ
Więcej informacji można uzyskać bezpośrednio od autora.
.SH UWAGI
Ten skrypt jest udostępniany na licencji GPL. Więcej szczegółów można znaleźć w pliku /usr/share/common-licenses/GPL lub skontaktować się z Free Software Foundation w celu uzyskania kopii.

